config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  get 'welcome/index'

  scope '/admin' do
    resources :users
  end

  resources :categories
  resources :topics
  resources :posts, except: :index

  get 'search/index'

  root to: 'welcome#index'

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user, optional: true
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  def self.search(query)
    return all.order('name ASC') if query.blank?

    where('LOWER(name) LIKE ?', "%#{query.downcase}%").order('name ASC')
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_categories, only: %i[new create edit update index]

  def index
    @topics = Topic.order('name DESC').paginate(page: params[:page], per_page: 3)
  end

  def show
    @user = @topic.user
    @associated_posts = @topic.posts.order('updated_at DESC').paginate(
      page: params[:page],
      per_page: 3
    )
  end

  def new; end

  def edit; end

  def create
    @topic.user_id = current_user.id

    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Topic was successfully destroyed.'
  end

  private

  def set_categories
    @categories = Category.order(:name)
  end

  def topic_params
    params.require(:topic).permit(
      :name,
      :description,
      :user_id,
      { category_ids: [] }
    )
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def created_by(user)
    return user.name if user

    'Destroyed user'
  end
end

app/views/topics/_form.html.haml
= render 'shared/errors', obj: topic
= form_with(model: topic) do |form|
  %div.form-group.row.mb-4
    = form.label :name, "Name:", class: "col-form-label fs-5 fw-bolder text-start"
    %div
      = form.text_area :name, class: "form-control shadow rounded", rows: 2
    = form.label :description, "Description:", class: "col-form-label fs-5 fw-bolder text-start"
    %div
      = form.text_area :description, class: "form-control shadow rounded", rows: 5
    = form.label :category_ids, "Select category:", class: "col-form-label fs-5 fw-bolder text-start"
    %div
      = form.collection_check_boxes(:category_ids, @categories, :id, :name) do |b|
        %p{class: "mb-1 text-start"}
          = b.check_box class: "form-check-input"
          = b.label
  %div.text-end
    = form.submit class: "btn btn-outline-success shadow"

app/views/topics/edit.html.haml
%div.container
  %div.card.text-center.shadow.rounded.mb-3.mt-3
    %div.card-header.fs-3.fw-bolder
      Edit topic:
    %div.card-body
      = render 'form', topic: @topic
    %div.card-footer
      = link_to 'Show', @topic, class: "btn btn-outline-primary"
      |
      = link_to 'Back', topics_path, class: "btn btn-outline-primary"

app/views/topics/index.html.haml
%div.container.mt-3.text-center
  %div.mb-3.fs-3.fw-bolder
    Topics:
= will_paginate(@topics,
  class: 'container custom-pagination text-center',
  inner_window: 1,
  outer_window: 0,
  previous_label: '<',
  next_label: '>')

%div.container
  - @topics.each do |topic|
    %div.card.text-center.shadow.rounded.mb-3.mt-3
      %div.card-header.text-start
        %div.fs-4.fw-bolder
          = topic.name
        %div.fs-6
          (
          = pluralize(topic.posts.count, 'post')
          )
        %div.mt-2
          - topic.categories.each do |cat|
            = link_to cat.name, category_path(cat), class: 'btn btn-outline-secondary btn-sm ms-1'
      %div.card-body.text-start
        %div.fs-6
          = truncate(topic.description, length: 100)
      %div.card-footer.text-end
        = link_to 'Discussion', topic, class: "btn btn-outline-primary m-1"
        - if can? :update, topic
          |
          = link_to 'Edit', edit_topic_path(topic), class: "btn btn-outline-primary m-1"
        - if can? :destroy, topic
          |
          = link_to 'Destroy', topic, method: :delete,
          data: { confirm: 'Are you sure?' },
          class: "btn btn-outline-danger m-1"

  %div.container.text-center.mb-3
    - if can? :create, Topic
      = link_to 'New Topic', new_topic_path, class: "btn btn-outline-success"

  = will_paginate(@topics,
    class: 'container custom-pagination text-center mb-2',
    inner_window: 1,
    outer_window: 0,
    previous_label: '<',
    next_label: '>')

app/views/topics/new.html.haml
%div.container
  %div.card.text-center.shadow.rounded.mb-3.mt-3
    %div.card-header.fs-3.fw-bolder
      New topic:
    %div.card-body
      = render 'form', topic: @topic
    %div.card-footer
      = link_to 'Back', topics_path, class: "btn btn-outline-primary"

app/views/topics/show.html.haml
%div.card.text-center.shadow.rounded.mb-3.mt-3
  %div.card-header
    %div.fs-4.fw-bolder
      = @topic.name
    %div.mt-2
      - @topic.categories.each do |cat|
        = link_to cat.name, category_path(cat), class: 'btn btn-outline-secondary btn-sm ms-1'
  %div.card-body.text-start
    %div
      %strong Created by:
      = created_by(@user)
      ,
    %div
      %strong Created at:
      = time_ago_in_words(@topic.created_at)
      ago,
    %div
      %strong edited:
      = time_ago_in_words(@topic.updated_at)
      ago.
    %hr
    = @topic.description
  %div.card-footer.text-end
    - if can? :update, @topic
      = link_to 'Edit', edit_topic_path(@topic), class: "btn btn-outline-primary"
      - if can? :destroy, @topic
        |
        = link_to 'Destroy', @topic, method: :delete,
        data: { confirm: 'Are you sure?' },
        class: "btn btn-outline-danger m-1"
      |
      = link_to 'Back', topics_path, class: "btn btn-outline-primary"

%div.container.mt-3.text-center
  %div.mb-3.fs-3.fw-bolder
    Discussion:

= will_paginate(@associated_posts,
  class: 'container custom-pagination text-center',
  inner_window: 1,
  outer_window: 0,
  previous_label: '<',
  next_label: '>')

%div.container.mb-3
  - if @associated_posts.present?
    - @associated_posts.each do |post|
      %div.card.text-center.shadow.rounded.mb-3.mt-3
        %div.card-header
          %div.fs-5.fw-bolder
            = created_by(post.user)
          %div.fs-6
            (
            = time_ago_in_words(post.updated_at)
            ago )
        %div.card-body.text-start
          %div.fs-6.fw-bolder
            = post.name
          %hr
          %div.fs-6
            = post.body
        %div.card-footer.text-end
          = link_to 'Details', post, class: "btn btn-outline-primary"
  - else
    %p.text-center
      "Discussion is empty."

%div.container.text-center.mb-3
  = link_to 'Add post', {controller: "posts", action: "new", topic_ref: @topic},
  class: "btn btn-outline-success"

= will_paginate(@associated_posts,
  class: 'container custom-pagination text-center mb-2',
  inner_window: 1,
  outer_window: 0,
  previous_label: '<',
  next_label: '>')