config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
          registrations: 'users/registrations'
        }

  get 'welcome/index'

  scope '/admin' do
    resources :users
  end

  resources :categories
  resources :topics
  resources :posts, except: :index

  get 'search/index'

  root to: 'welcome#index'

end

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white" id="sticky-footer">
  <div class="container text-center">
    <small>
      Copyright &copy;
      <%= link_to 'Krzysztof Kiec', 'https://github.com/KKIEC', class: 'text-white' %>
    </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if name=="error" %>
    <%= content_tag :div, msg, id: "flash_#{name}", class: "alert alert-danger" %>
  <% elsif name=="notice" %>
    <%= content_tag :div, msg, id: "flash_#{name}", class: "alert alert-success" %>
  <% else %>
    <%= content_tag :div, msg, id: "flash_#{name}", class: "alert alert-warning" %>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div id="myModal">
  <div id="mCont" class="alert alert-danger fade show text-center">
    <div class="alert-heading">
      <strong>CONFIRMATION REQUIRED</strong>
    </div>
    <div>
      <p>Do you want permanent destroy this object?</p>
    </div>
    <div>
      <button id="btnYes" class="btn btn-danger">Destroy</button>
      <button id="btnNo" class="btn btn-success">Cancel</button>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'KK-FORUM', root_path, class: 'navbar-brand', id: 'logo' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user&.admin? %>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Topics", topics_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %> (<%= current_user.email %>)
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Delete profile', registration_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" }%></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <%= form_with url: search_index_path, method: :get, class: 'd-flex' do |f| %>
        <%= f.text_field :search, class: 'form-control me-2', placeholder: 'Search by name' %>
        <%= f.submit 'Search', name: nil, class: 'btn btn-outline-light me-2' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KK-Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>

    <div id="page-content">
      <%= render 'layouts/messages' %>
      <div class="container-sm col-sm-6">
        <%= yield %>
      </div>
      <%= render 'layouts/modal' %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>